backend/controllers/ProcessController.php
<?php
namespace backend\controllers;

use Yii;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use common\models\LoginForm;

use yii\web\Response;

/**
 * Site controller
 */
class ProcessController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['login', 'error'],
                        'allow' => true,
                    ],
                    [
                        'actions' => ['index', 'test'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {

        return $this->render('index');
    }

    public function actionTest()
    {
        Yii::$app->response->format = Response::FORMAT_JSON;

        $cmd = "python ".Yii::getAlias('@app')."/../python/predict.py";
        exec($cmd,$output,$rv);

        return $output[0];


    }


}

backend/views/process/index.php
<?php
/**
 * Created by PhpStorm.
 * User: user
 * Date: 11/9/2017
 * Time: 7:30 PM
 */

use yii\helpers\Url;
use yii\helpers\Html;

/* @var $this yii\web\View */

$this->title = 'Process by Python | GTD PREDICTIVE ANALYSIS';
?>

<div class="box b-a white">
    <div class="box-header"></div>
    <div class="box-body">
        <p class="btn-groups text-center">
            <button id="btnUpdate" class="btn btn-outline b-primary text-primary">Update predictions</button>
            <button class="btn btn-outline b-black text-black disabled">Retrain module</button>
        </p>
    </div>
</div>


<!-- RESULTS -->
<div class="text-center">
    <div id="processTime" class="h4 text-center "></div>
    <div id="processResult" class="h3"></div>
</div>



<script type="text/javascript">

    $(document).ready(function() {





        $("#btnUpdate").click(function(){

            $("#processTime").html("0%")
            $("#processTime").show();

            $("#processResult").hide();

            var interval = setInterval(function(){
                if (window.Pace.bar.progress!=100){
                    $("#processTime").html(Math.round(window.Pace.bar.progress)+'%');
                }
            },100);


            var start_time = new Date().getTime();

            jQuery.ajax({
                url: '<?= Url::to( [ '/process/test' ] ); ?>',
                type: 'GET',
                contentType: 'application/json',
//                xhrFields: {
//                    onprogress: function (e) {
//                        //console.log(window.Pace.bar.progress);
//                        if (e.lengthComputable) {
//                            console.log(e.loaded / e.total * 100 + '%');
//                        }
//                    }
//                },
                success: function (data){
//                    #alert(data);
//                    #var request_time = new Date().getTime() - start_time;
//                    alert(request_time);
                      $("#processResult").show();
                      $("#processResult").html(data)

                }
            }).complete(function() {
                $("#processTime").html("0%")
                $("#processTime").hide();
            });
        });

    });
</script>