backend/controllers/ApiController.php
<?php
namespace backend\controllers;

use Yii;
use yii\helpers\Url;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use app\models\ExtractedDataNozzle;
use yii\web\Response;

/**
 * Site controller
 */
class ApiController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['index'],
                        'allow' => true,
                    ],
                    [
                        'actions' => ['logout', 'index','failuretotal', 'stationsummary', 'predictionreport', 'predictionreportbystation'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    public function beforeAction($action) {
        $this->enableCsrfValidation = false;
        return parent::beforeAction($action);
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    public function actionIndex()
    {
        echo 'Salom';
    }


    public function actionFailuretotal()
    {
        Yii::$app->response->format = Response::FORMAT_JSON;

        //id, case_id, station_id, business_partner_name, pump, gas_type, creation_date, completion_date, days_to_action, lifetime,
        // transaction_days, transaction_count, adjusted_transaction_count, total_volume, adjusted_total_volume

        $model = (new \yii\db\Query())
            ->select('station_id, COUNT(*) as num_failure')
            ->from('extracted_data_nozzle')
            //->where(['gas_type' => '95'])
            ->where(['>', 'lifetime', 0])
            ->groupBy(['station_id'])
            ->all();

        $my_data=[];
        foreach ($model as $key => $value) {
            $my_data['station_id'][$key] =$value['station_id'];
            $my_data['num_failure'][$key] =$value['num_failure'];
        }

        //$data=array_map(create_function('$m','return $m->getAttributes(array(\'pump\',\'lifetime\'));'),$my_data);

        echo json_encode($my_data);
    }

    public function actionStationsummary()
    {
        Yii::$app->response->format = Response::FORMAT_JSON;
        $station_id=$_POST['station_id'];
        $gas_type=$_POST['gas_type'];
//        SELECT e.pump, e.lifetime, p.lifetime_predicted
//        FROM extracted_data_nozzle e
//        left join data_nozzle_predicted as p on p.related_id=e.id
//        where e.lifetime>0 and station_id='RYB0715'
//        order by e.pump

        $model = (new \yii\db\Query())
            ->select('e.pump, e.lifetime, p.lifetime_predicted')
            ->from('extracted_data_nozzle as e')
            ->leftJoin('data_nozzle_predicted as p', 'p.related_id=e.id')
            ->where(['>', 'lifetime', 0])
            ->andWhere(['=', 'e.station_id', $station_id])
            ->andWhere(['=', 'e.gas_type', $gas_type])
            ->groupBy(['e.pump'])
            ->all();

        $my_data=[];
        foreach ($model as $key => $value) {
            $my_data['pump'][$key] =$value['pump'];
            $my_data['lifetime'][$key] =$value['lifetime'];
            $my_data['lifetime_predicted'][$key] =$value['lifetime_predicted'];
        }

        //$data=array_map(create_function('$m','return $m->getAttributes(array(\'pump\',\'lifetime\'));'),$my_data);

        echo json_encode($my_data);
    }


// To generate prediction report on predictions/index.php
    public function actionPredictionreport()
    {
        Yii::$app->response->format = Response::FORMAT_JSON;

        //id, case_id, station_id, business_partner_name, pump, gas_type, creation_date, completion_date, days_to_action, lifetime,
        // transaction_days, transaction_count, adjusted_transaction_count, total_volume, adjusted_total_volume

        $model = (new \yii\db\Query())
            ->select('a.id, a.business_partner_name, a.pump, a.gas_type, b.lifetime_predicted, a.completion_date')
            ->from('extracted_data_nozzle as a')
            ->leftJoin('data_nozzle_predicted as b', 'b.related_id=a.id')
            //->where(['gas_type' => '95'])
            ->where(['>', 'lifetime', 0])
            // ->groupBy(['a.business_partner_name'])
            ->all();

        // $object=NULL;
        $my_data=[];
        foreach ($model as $key => $value) {

            $my_data['data'][$key]['id']=$value['id'];
            $my_data['data'][$key]['business_partner_name']=$value['business_partner_name'];
            $my_data['data'][$key]['pump']=$value['pump'];
            $my_data['data'][$key]['gas_type']=$value['gas_type'];
            $my_data['data'][$key]['lifetime_predicted']=$value['lifetime_predicted'];
            $my_data['data'][$key]['completion_date']=$value['completion_date'];
        }



        //$data=array_map(create_function('$m','return $m->getAttributes(array(\'pump\',\'lifetime\'));'),$my_data);

        echo json_encode($my_data);
        // echo json_encode($my_data);
    }

    // To generate prediction report on predictions/index.php
    public function actionPredictionreportbystation()
    {
        Yii::$app->response->format = Response::FORMAT_JSON;
        $station_id=$_POST['station_id'];
        $gas_type=$_POST['gas_type'];

            $model = (new \yii\db\Query())
            ->select('a.id, a.business_partner_name, a.pump, a.gas_type, b.lifetime_predicted, a.station_id, a.gas_type, a.completion_date')
            ->from('extracted_data_nozzle as a')
            ->leftJoin('data_nozzle_predicted as b', 'b.related_id=a.id')
            //->where(['gas_type' => '95'])
            ->where(['>', 'lifetime', 0])
            ->andWhere(['=', 'a.station_id', $station_id])
            ->andWhere(['=', 'a.gas_type', $gas_type])
            // ->groupBy(['a.business_partner_name'])
            ->all();

        // $gas_type="95";
        // $station_id="RYB0715";
        //id, case_id, station_id, business_partner_name, pump, gas_type, creation_date, completion_date, days_to_action, lifetime,
        // transaction_days, transaction_count, adjusted_transaction_count, total_volume, adjusted_total_volume

        // $object=NULL;
        $my_data=[];
        foreach ($model as $key => $value) {

            $my_data['data'][$key]['id']=$value['id'];
            $my_data['data'][$key]['business_partner_name']=$value['business_partner_name'];
            $my_data['data'][$key]['pump']=$value['pump'];
            $my_data['data'][$key]['gas_type']=$value['gas_type'];
            $my_data['data'][$key]['lifetime_predicted']=$value['lifetime_predicted'];
            $my_data['data'][$key]['completion_date']=$value['completion_date'];
        }



        //$data=array_map(create_function('$m','return $m->getAttributes(array(\'pump\',\'lifetime\'));'),$my_data);

        echo json_encode($my_data);
        // echo json_encode($my_data);
    }




}

backend/controllers/DashboardController.php
<?php
namespace backend\controllers;

use Yii;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use common\models\LoginForm;

/**
 * Site controller
 */
class DashboardController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['login', 'error'],
                        'allow' => true,
                    ],
                    [
                        'actions' => ['index', 'petrol'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    public function beforeAction($action) {
        $this->enableCsrfValidation = false;
        return parent::beforeAction($action);
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        $model_failures_all = (new \yii\db\Query())
            ->select('e.pump, e.lifetime')
            ->from('extracted_data_nozzle as e')
            ->all();

        $model_failures_notnull = (new \yii\db\Query())
            ->select('e.pump, e.lifetime')
            ->from('extracted_data_nozzle as e')
            ->where(['>', 'lifetime', 0])
            ->all();

        $model_transactions_sum_all = (new \yii\db\Query())
            ->select('sum(e.transaction_count) as total_transactions')
            ->from('extracted_data_nozzle as e')
            ->one();

        $model_transactions_sum_failured_pump = (new \yii\db\Query())
            ->select('sum(e.transaction_count) as total_transactions')
            ->from('extracted_data_nozzle as e')
            ->where(['>', 'lifetime', 0])
            ->one();

        $model_parts_all = (new \yii\db\Query())
            ->select('SUM(I1_1012+I1_1026+I1_105+I1_109+I1_1123+I1_113+I1_1141+I1_1142+I1_1143+I1_1183+I1_136+I1_1469+I1_1475+I1_1487+I1_1516+I1_153+I1_1628+I1_1653+I1_169+I1_1702+I1_171+I1_1737+I1_1739+I1_1740+I1_175+I1_176+I1_1785+I1_1819+I1_1820+I1_1874+I1_1900+I1_1902+I1_1937+I1_1938+I1_1960+I1_1961+I1_1962+I1_1967+I1_2058+I1_2060+I1_2061+I1_208+I1_2131+I1_2132+I1_2133+I1_2158+I1_2281+I1_2329+I1_245+I1_25+I1_250+I1_2516+I1_2517+I1_2518+I1_2519+I1_2520+I1_2521+I1_256+I1_2566+I1_2567+I1_2569+I1_2571+I1_2591+I1_2617+I1_2629+I1_2631+I1_2713+I1_2749+I1_2758+I1_2769+I1_279+I1_2796+I1_2800+I1_2871+I1_3053+I1_3054+I1_364+I1_369+I1_415+I1_425+I1_436+I1_449+I1_456+I1_471+I1_473+I1_475+I1_478+I1_486+I1_491+I1_495+I1_513+I1_517+I1_552+I1_556+I1_557+I1_559+I1_569+I1_570+I1_599+I1_60+I1_607+I1_624+I1_627+I1_628+I1_629+I1_645+I1_646+I1_647+I1_650+I1_651+I1_656+I1_660+I1_668+I1_670+I1_671+I1_673+I1_675+I1_676+I1_677+I1_678+I1_679+I1_767+I1_82+I1_918) as total_parts')
            ->from('parts_encode_nozzle as p')
            ->leftJoin('data_nozzle_predicted as d', 'd.related_id=p.id')
            ->one();

        $model_parts_notnull = (new \yii\db\Query())
            ->select('e.lifetime, SUM(I1_1012+I1_1026+I1_105+I1_109+I1_1123+I1_113+I1_1141+I1_1142+I1_1143+I1_1183+I1_136+I1_1469+I1_1475+I1_1487+I1_1516+I1_153+I1_1628+I1_1653+I1_169+I1_1702+I1_171+I1_1737+I1_1739+I1_1740+I1_175+I1_176+I1_1785+I1_1819+I1_1820+I1_1874+I1_1900+I1_1902+I1_1937+I1_1938+I1_1960+I1_1961+I1_1962+I1_1967+I1_2058+I1_2060+I1_2061+I1_208+I1_2131+I1_2132+I1_2133+I1_2158+I1_2281+I1_2329+I1_245+I1_25+I1_250+I1_2516+I1_2517+I1_2518+I1_2519+I1_2520+I1_2521+I1_256+I1_2566+I1_2567+I1_2569+I1_2571+I1_2591+I1_2617+I1_2629+I1_2631+I1_2713+I1_2749+I1_2758+I1_2769+I1_279+I1_2796+I1_2800+I1_2871+I1_3053+I1_3054+I1_364+I1_369+I1_415+I1_425+I1_436+I1_449+I1_456+I1_471+I1_473+I1_475+I1_478+I1_486+I1_491+I1_495+I1_513+I1_517+I1_552+I1_556+I1_557+I1_559+I1_569+I1_570+I1_599+I1_60+I1_607+I1_624+I1_627+I1_628+I1_629+I1_645+I1_646+I1_647+I1_650+I1_651+I1_656+I1_660+I1_668+I1_670+I1_671+I1_673+I1_675+I1_676+I1_677+I1_678+I1_679+I1_767+I1_82+I1_918) as total_parts')
            ->from('parts_encode_nozzle as p')
            ->leftJoin('extracted_data_nozzle as e', 'e.id=p.id')
            ->where(['>', 'e.lifetime', 0])
            ->one();



        return $this->render('index',array(
                'count_failures_all'=>count($model_failures_all),
                'count_failures_notnull'=>count($model_failures_notnull),
                'transactions_sum_all'=>$model_transactions_sum_all['total_transactions'],
                'transactions_sum_failured_pump'=>$model_transactions_sum_failured_pump['total_transactions'],
                'total_parts_all'=>$model_parts_all['total_parts'],
                'total_parts_notnull'=>$model_parts_notnull['total_parts'],

                ));
    }

    public function actionPetrol()
    {
        $request = Yii::$app->request;

//        SELECT e.business_partner_name, e.pump, COUNT(*) as pump_failure_reports
//        FROM extracted_data_nozzle e
//        where station_id='RYB0715'
//        GROUP by e.pump

        $model_station = (new \yii\db\Query())
            ->select('e.business_partner_name, e.pump, COUNT(*) as pump_failure_reports, e.lifetime')
            ->from('extracted_data_nozzle as e')
            ->where(['=', 'e.station_id', $_POST['station_id']])
            ->groupBy(['e.pump'])
            ->all();

//        SELECT e.gas_type, COUNT(*) as num_gastype_failure
//        FROM extracted_data_nozzle e
//        where e.station_id='RYB0715' and e.lifetime>0
//        GROUP by e.gas_type

        $model_gas = (new \yii\db\Query())
            ->select('e.gas_type, COUNT(*) as num_gastype_failure')
            ->from('extracted_data_nozzle as e')
            ->where(['>', 'lifetime', 0])
            ->andWhere(['=', 'e.station_id', $_POST['station_id']])
            ->groupBy(['e.gas_type'])
            ->all();


        if (Yii::$app->request->isPost){
            return $this->renderPartial('petrol',array(
                'station_data'=>$model_station,
                'dataset'=>$_POST['dataset'],
                'station_id'=>$_POST['station_id'],
                'total_failure'=>$_POST['total_failure'],
                'gastype_data'=>$model_gas

            ), false,true);
        }

    }


}

backend/views/dashboard/index.php
<?php
/**
 * Created by PhpStorm.
 * User: user
 * Date: 11/9/2017
 * Time: 7:30 PM
 */

use yii\helpers\Url;
use yii\helpers\Html;

/* @var $this yii\web\View */

$this->title = 'DASHBOARD | GTD PREDICTIVE ANALYSIS';
?>

<div class="row">
    <div class="col-xs-12 col-sm-4">
        <div class="box p-a">
            <div class="pull-left m-r">
	            <span class="w-48 rounded  accent">
	              <i class="material-icons"></i>
	            </span>
            </div>
            <div class="clear">
                <h4 class="m-a-0 text-lg _300"><?=number_format($count_failures_notnull)?> <span class="text-sm">Total Failures</span></h4>
                <small class="text-muted">from <?=number_format($count_failures_all)?> records</small>
            </div>
        </div>
    </div>
    <div class="col-xs-6 col-sm-4">
        <div class="box p-a">
            <div class="pull-left m-r">
	            <span class="w-48 rounded primary">
	              <i class="material-icons"></i>
	            </span>
            </div>
            <div class="clear">
                <h4 class="m-a-0 text-lg _300"><a href=""><?=number_format($transactions_sum_failured_pump)?><span class="text-sm"> Transactions</span></a></h4>
                <small class="text-muted">from <span><?=number_format($transactions_sum_all, 0)?></span> transactions</small>
            </div>
        </div>
    </div>
    <div class="col-xs-6 col-sm-4">
        <div class="box p-a">
            <div class="pull-left m-r">
	            <span class="w-48 rounded warn">
	              <i class="material-icons"></i>
	            </span>
            </div>
            <div class="clear">
                <h4 class="m-a-0 text-lg _300"><a href=""><?=number_format($total_parts_notnull)?> <span class="text-sm">Equipments Repaired</span></a></h4>
                <small class="text-muted">Total <?=number_format($total_parts_all)?> Replacements</small>
            </div>
        </div>
    </div>
</div>

<!-- GRAPHS -->
<div class="box b-a">
    <div class="box-header">
        <h3>Number of Failures</h3>
        <small>Presented number of existing and predicted failures for each petrol station.</small>
    </div>
    <div class="box-body white">

        <div id="chart-container">
            <canvas id="graphCanvas" style="width:100%;height:100%"></canvas>
        </div>
    </div>
</div>



<!-- Response -->
<div id="petrol-data" class=""></div>

<script type="text/javascript">
    $(document).ready(function () {
        //showGraph();
    });


    $.ajax('<?= Url::to( [ '/api/failuretotal' ] ); ?>').done(function (data) {
        var chartdata = {
            labels: data.station_id,
            datasets: [
                {
                    label: 'Number of Failures',
                    backgroundColor: '#2ec7c9',
                    borderColor: '#07a2a4',
                    hoverBackgroundColor: '#f77a99', //'#59678c',
                    hoverBorderColor: '#f44455',
                    data: data.num_failure
                }
            ]
        };

        var graphTarget = $("#graphCanvas");

        var barGraph = new Chart(graphTarget, {
            type: 'bar',
            data: chartdata,
            options: {
                "hover": {
                    "animationDuration": 0,
                     onHover: function(e) {
                        var point = this.getElementAtEvent(e);
                        if (point.length) e.target.style.cursor = 'pointer';
                        else e.target.style.cursor = 'default';
                    }
                },
                "animation": {
                    "duration": 1,
                    "onComplete": function() {
                        var chartInstance = this.chart,
                            ctx = chartInstance.ctx;

                        ctx.font = Chart.helpers.fontString(Chart.defaults.global.defaultFontSize, Chart.defaults.global.defaultFontStyle, Chart.defaults.global.defaultFontFamily);
                        ctx.textAlign = 'center';
                        ctx.textBaseline = 'bottom';

                        this.data.datasets.forEach(function(dataset, i) {
                            var meta = chartInstance.controller.getDatasetMeta(i);
                            meta.data.forEach(function(bar, index) {
                                var data = dataset.data[index];
                                ctx.fillText(data, bar._model.x, bar._model.y - 5);
                            });
                        });
                    }
                },
                legend: {
                    "display": false,
                    onHover: function(e) {
                        e.target.style.cursor = 'pointer';
                    }
                },
                tooltips: {
                    "enabled": true
                },
                scales: {
                    yAxes: [{
                        display: true,
                        gridLines: {
                            display: true
                        },
                        scaleLabel: {
                            display: true,
                            labelString: 'Num. of Failures',
                            fontColor: "#aaa",
                            fontSize:11
                        }
                    }],
                    xAxes: [{
                        gridLines: {
                            display: false
                        },
                        ticks: {
                            beginAtZero: true
                        },

                        scaleLabel: {
                            display: true,
                            labelString: 'Stations',
                            fontColor: "#aaa",
                            fontSize:11
                        }
                    }]
                },
                onClick: function(c,i) {
                    e = i[0];
                    var x_value = this.data.labels[e._index];
                    var y_value = this.data.datasets[0].data[e._index];
                    getReport(e._index,x_value,y_value)
                }
            }
        });

    });

    function getReport(index,x,y) {
        $.ajax({
            method: "POST",
            url: "<?= Url::to(['/dashboard/petrol']); ?>",
            data: {'dataset': index, 'station_id':x, 'total_failure':y}
        }).done(function (response) {
            $("#petrol-data").html(response);
        });
    }

    




</script>

<!-- ############ PAGE END-->